# Generated by Django 3.2.6 on 2021-08-08 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(default=0, verbose_name='Income Amount')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PAID', 'PAID'), ('DELAYED', 'DELAYED')], default='NEW', max_length=7, verbose_name='Status Tax')),
                ('tax_amount', models.FloatField(blank=True, null=True, verbose_name='Tax Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tax_accountant', to=settings.AUTH_USER_MODEL)),
                ('tax_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tax_payer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxs',
            },
        ),
    ]
