# Generated by Django 3.2.6 on 2021-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltax',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
