# Generated by Django 3.2.6 on 2021-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_auto_20210808_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='fines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
